// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekepgnrvewkqkjgexgly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZXBnbnJ2ZXdrcWtqZ2V4Z2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ4NTI1NTUsImV4cCI6MjA1MDQyODU1NX0.q6QKreoTTPQy4cWPLUBJ6X9na6Ji7K4oa3qQAOKzoig";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);